#! /bin/bash
ros2 topic pub -r 10 -t 10 /cmd_vel geometry_msgs/msg/Twist "{linear: {x: 0.25, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.0}}" && ros2 topic pub --once /cmd_vel geometry_msgs/msg/Twist "{}"
