/teleop_twist_joy_node:
  ros__parameters:
    # --- 頻率控制核心設定 ---
    # 限制 teleop 的最高重複發送頻率 (Hz) 降至 15Hz，保護下位機 ESP32
    autorepeat_rate: 10.0
    
    # --- 按鍵映射 ---
    require_enable_button: true
    enable_button: 4           # PS4 L1
    
    axis_linear:
      x: 1                     # 左搖桿上下
    scale_linear:
      x: 0.2
      
    axis_angular:
      yaw: 3                   # 右搖桿左右
    scale_angular:
      yaw: 1.8
